### ISSUE TITLE
multiple firmata versions

### ISSUE THREAD

**Issue by soundanalogous** [noopkat/firmata-party#27]
I encourage you to explore a way to provide a choice in which version of firmata is installed. I'm making StandardFirmata more of a legacy version - not adding any major new features so that it will still run on popular architectures like the ATmega328p and ATmega32u4. [StandardFirmataPlus](https://github.com/firmata/arduino/tree/master/examples/StandardFirmataPlus) is the recommended more full-featured version going forward.

One approach would be to use [firmata-builder](https://github.com/firmata/firmata-builder). This will generate sketch files dynamically based on some input. You could identify a few popular configurations and allow the user to choose one via a command line argument. I guess you need the `.hex` file though so this wouldn't help unless there is another node process that can generate a hex file from an `.ino` file.

Just some food for thought.

**Comment by noopkat** [comment]
@soundanalogous thank you for the feedback! I didn't realise StandardFirmata was becoming legacy. For now I can precompile StandardFirmataPlus and create an option to choose which Firmata, with Plus being the default.

I will definitely look into using `firmata-builder` for this going forward, it looks great.

Thanks again :grin:

**Comment by soundanalogous** [comment]
np. A precompiled StandardFirmataPlus as default sounds like a good solution. It's great having some cli alternatives to the IDE. Thanks for your work on this!
