### ISSUE TITLE
Can't flash a pro-mini despite being in the supported list

### ISSUE THREAD

**Issue by aufflick** [noopkat/firmata-party#46]
There are two problems, you can't specify a port for avrgirl to use, and the firmware is called StandardFirmata-3v.cpp.hex

**Comment by noopkat** [comment]
closing this, because of your awesome pull request 😁

**Comment by aufflick** [comment]
Yay! You sure know how to make a contributor feel great :D The _actual_ project of writing a Swift native firmata driver has slowed in the face of life's onslaughts sadly.

**Comment by noopkat** [comment]
aha, I know those feels. Life is generally an open source killjoy. I wish you the best with future progress on your driver
