### ISSUE TITLE
Update / sync boards list with avrgirl-arduino

### ISSUE THREAD

**Issue by noopkat** [noopkat/firmata-party#63]
The boards list in the README and the `list` command is out of date.
These two resources need to be synced with the boards that [avrgirl-arduino](https://github.com/noopkat/avrgirl-arduino) currently supports.

**Comment by rmjjjt** [comment]
Hi, 
I've not contributed to anything OS before, but I'm sure I can do this! 
It looks like it is the boards variable that needs updating as well as the readme. Is that correct?
If so, and it is still open - I'll do it. :)

**Comment by noopkat** [comment]
Hi @rmjjjt! 

You're spot on - that's what needs to be changed. This is still open and not owned by anyone, so I'd be *very* appreciative if you could work on this 😄 Let me know if yo have further questions!

**Comment by rmjjjt** [comment]
Do I need to do anything to own/be assigned to it?
I'll look at it tomorrow. :)

**Comment by noopkat** [comment]
@rmjjjt I just tried adding you as the assignee, however it might be my flaky internet preventing me from doing so. Consider yourself assigned regardless 😄

**Comment by noopkat** [comment]
closing this as the work is merged. Thank you again! ✨

**Comment by rmjjjt** [comment]
No problem, glad I could help. :)
