### ISSUE TITLE
If installed locally, can't find firmata file

### ISSUE THREAD

**Issue by KatieK2** [noopkat/firmata-party#70]
If firmata-party is installed locally (I.E. without the -g flag), then I got this error:

    { Error: ENOENT: no such file or directory, scandir '/Users/katiek/Documents/j5/cplay/node_modules/firmata-party/node_modules/avrgirl-arduino/junk/hex/circuit-playground-classic'
        at Error (native)
      errno: -2,
      code: 'ENOENT',
      syscall: 'scandir',
      path: '/Users/katiek/Documents/j5/cplay/node_modules/firmata-party/node_modules/avrgirl-arduino/junk/hex/circuit-playground-classic' }

It seems that firmata-party could not find the `/avrgirl-arduino/` path when it was relative from the installed / local directory. Probably there is an absolute path somewhere.

Firmata did work fine after installing firmata-party globally.

**Comment by noopkat** [comment]
Hi @KatieK2!

Thanks for reporting this. I think the reason why it doesn't work as a non global package is that I didn't design it for a local use case and assumed it'd always be installed globally (I should have documented this doh). 

I can now see why you'd want to use it locally - for a setup script perhaps? Let me know if this is correct 😄 Are you calling this from within a custom npm script, or programmatically somewhere else?

One way to fix this for local use would be to test for the location of the avrgirl-arduino dependency depending on whether it's being used globally or locally.

I'll work on this later in the week when I get a moment, and will keep you updated 🤞

**Comment by KatieK2** [comment]
Hi @noopkat! 

Ha, it's nowhere near this complicated. I've just been trying to keep my npm installs more tidy these days. In the past I've gotten into trouble by installing globally willy-nilly. After getting help from some folks, I've gotten the advice to install *everything* locally, even though *so many packages* want to be installed globally. It's mostly to avoid any possible chance of breaking some weird edge case in one project by upgrading a global install.

Being able to be script with this does sound awesome, though! But there is no rush whatsoever here - I just saw a problem and figured I'd report it. :)

If you do add local install option, it would also be nice to add the path to the bin/firmata-party.js file into the user's path. (I dunno if this is complicated; just something I thought of.)

**Comment by noopkat** [comment]
thanks to courajs for pointing me at this which should help fix this issue when I get the time https://nodejs.org/api/modules.html#modules_require_resolve

**Comment by whitfin** [comment]
Hi @KatieK2!

I have filed a PR for this over in #73; the issue doesn't seem to occur for me anymore so please try it out and let me know if you need me to make any changes!

@noopkat I hope you don't mind me poaching 😀

**Comment by KatieK2** [comment]
Hi @whitfin! Great, I'd like to test this.

What would be the easiest way to un-install my current globally installed firmata-party? And, uhh, how to I test-install @whitfin's new changes?

Thanks!

**Comment by whitfin** [comment]
Aloha @KatieK2!

I'm not sure about uninstalling; you can probably just `npm uninstall -g firmata-party` and be ok (but I'm not sure if there's any other cleanup required). For testing though, it might be possible to test out without removing the global first; I believe `npm` scripts will look locally first before they look globally.

If so, you can clone the forked repo and install it locally into the project you're testing it with:

```
# change directory at this point to somewhere like /tmp 
cd /tmp

# clone the branch from the fork repo
git clone -b issue-70-local-install https://github.com/whitfin/firmata-party.git

# change directory at this point to the root of your project
cd ~/my-project

# this will install the cloned version 
npm install /tmp/firmata-party

# test your scripts!
```

**Comment by noopkat** [comment]
this issue is now fixed! 💯  thanks @whitfin
