### ISSUE TITLE
failing installation in Mint 19

### ISSUE THREAD

**Issue by jcabrerazuniga** [noopkat/firmata-party#74]
I tried:

npm install -g firmata-party
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t https://github.com/noopkat/browser-serialport.git
npm ERR! 
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joseccz/.npm/_logs/2018-09-22T17_30_19_469Z-debug.log

I am using linux mint 19 and node version v10.11.0

**Comment by jcabrerazuniga** [comment]
installed git

**Comment by noopkat** [comment]
@jcabrerazuniga glad you got it figured out 😄

**Comment by rokit685** [comment]
Podrían decirme como han solucionado el problema, ya que he instalado git pero el problema continua.
Aqui dejo el codigo que me aparece:

C:\Users\David>npm install -g firmata-party
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t https://github.com/noopkat/browser-serialport.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2020-03-07T13_22_20_466Z-debug.log

ademas installogit y todo parece estar bien:

C:\Users\David>npm install --save npm-git-install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\David\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\David\package.json'
npm WARN David No description
npm WARN David No repository field.
npm WARN David No README data
npm WARN David No license field.

+ npm-git-install@0.3.0
updated 1 package and audited 110 packages in 3.173s
found 0 vulnerabilities

AYUDAAA

**Comment by noopkat** [comment]
Hola @rokit685,

¿Qué programa de terminal estás usando con npm? 
Por ejemplo Command Prompt, WSL, WSL2, Powershell, Git-Bash?
