### ISSUE TITLE
i think find a bug or something go wrong

### ISSUE THREAD

**Issue by Darkerc** [noopkat/firmata-party#77]
Excuse me, i trying to install firmata-party but a have a error about this:
===================================================
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/noopkat/browser-serialport.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
=======================================================
i install "npm install -g firmata-party" and have node 10.16 but is not working i need help!!

**Comment by noopkat** [comment]
Hi thanks for reporting! Could you double check that you have git installed
in your machine and let me know? It’s required for one of the dependencies
to be installed. The error log you shared looks like it’s pointing to that
as the issue (can’t find git on your path/machine).

**Comment by Darkerc** [comment]
Yeah i have git  installed, Is nesesary use the git console to install the module?

**Comment by Darkerc** [comment]
Ye i use git console and works, anyway thanks for help ^.^

**Comment by noopkat** [comment]
no worries!
